### ISSUE TITLE
Custom updater

### ISSUE THREAD

**Issue by backisen** [isabellaalstrom/pollenkoll-card#10]
Är det möjligt att lägga till detta card till custom updater för att förenkla övervakningen och uppdateringen när nya versioner kommer?

**Comment by isabellaalstrom** [comment]
Tillagd, borde dyka upp under dagen.

**Comment by backisen** [comment]
Det har fortfarande inte dykt upp. Är det normalt?

**Comment by isabellaalstrom** [comment]
Jag har missat en sak ser jag. Fixar i helgen.

**Comment by isabellaalstrom** [comment]
Ska vara inne nu (jag ser den).

**Comment by Ranur** [comment]
Ser du även Sälg / Vide? Där får jag "unknown på sensorn.  En annan spännande grej är att jag på Ambrosia dag 2 får level: i.u övriga dagar level: i.h, men jag issar det är i sensorn felet ligger
