### ISSUE TITLE
Problems on mac

### ISSUE THREAD

**Issue by folrewef** [isabellaalstrom/pollenkoll-card#11]
I have installed the latest version using svg. It works on my iPhone and on my Ipad. But on my Mac (Safari) I only get small boxes with a  ?.

Further, if I add sälg/ vide everything in the view disappears (only on Mac - still working on iPhone and iPad)!

**Comment by isabellaalstrom** [comment]
You need to write it exactly like in the example for sälg / vide. Space on both sides of / 

Does the console log in safari say anything?

**Comment by folrewef** [comment]
Solved. I had emptied the cache on my iMac but not reloaded the page. Sorry for the trouble. Great work by the way.
