### ISSUE TITLE
Show_state: different sizes

### ISSUE THREAD

**Issue by folrewef** [isabellaalstrom/pollenkoll-card#14]
When I set show_state to false the status symbols change size:

 Without show_state:
(https://user-images.githubusercontent.com/43371683/55943882-c049b480-5c47-11e9-9636-5fb560847750.png)

With show_state: false
(https://user-images.githubusercontent.com/43371683/55955147-e16acf00-5c60-11e9-97b0-fd87153beacd.png)

On Mac with Safari

**Comment by isabellaalstrom** [comment]
That's interesting! 😄 Will see what I can do.

**Comment by folrewef** [comment]
Same on iPad and iPhone in iOS Companion

**Comment by isabellaalstrom** [comment]
A workaround until I get around to this is using `compact: true` together with `show_state: false`

**Comment by folrewef** [comment]
To me the workaround is great. Actually I prefer compact. :)

**Comment by fldc** [comment]
Unfortunately the icons are still different sizes using compact and show_state false here. Well, the ambrosia one is. :)

**Comment by isabellaalstrom** [comment]
I think everything will be fixed with the images in just released 0.1.0.
