### ISSUE TITLE
Björk stopped working with 0.92

### ISSUE THREAD

**Issue by folrewef** [isabellaalstrom/pollenkoll-card#18]
Just updated to 0.92, got my manifest.json working and restarted. The Bjork symbols do not work anymore. This may be an error of the sensor pollenniva. I see that I generates H+ rather than a number (6).

**Comment by folrewef** [comment]
I noticed that there are 8 states with the highest being H+, which is not defined in pollenniva. That's why H+ becomes H+ (and not 7). Temporarily solved it by adding "H+": 6 to the states list in sensor.py.

**Comment by folrewef** [comment]
Of course it has nothing to do with 0.92. Just coincidence.

**Comment by isabellaalstrom** [comment]
There is a new version of the component out that takes this into account, over at that repo. Then you only need to either download the new *7-images I've uploaded here or just copy your *6-images and rename the copies to *7, it's the same state for 6 and 7.
