### ISSUE TITLE
Sälg / vide saknas

### ISSUE THREAD

**Issue by krissen** [isabellaalstrom/pollenkoll-card#2]
Vet du känner till det, men öppnar en issue ändå, så att säga: sälg / vide saknas. Inte byggt lovelace-kort, men kikade lite i källkoden, och undrar om det skulle räcka att du ändrar

```
        else if (allergen == "sälg") {
        allergen = "salg"
```

till

```
      else if (allergen == "sälg") {
        allergen = "salg_vide"
```

Eftersom sensorn heter `sensor.pollenniva_STAD_salg_vide_day_0` medan jag tror rader som dem nedan förutsätter `sensor.pollenniva_STAD_salg_day_0`.

```
dict.day1 = hass.states[`sensor.pollenniva_${city}_${allergen}_day_0`],
dict.day2 = hass.states[`sensor.pollenniva_${city}_${allergen}_day_1`],
dict.day3 = hass.states[`sensor.pollenniva_${city}_${allergen}_day_2`]
```

Måhända skulle bildfilerna också behöva döpas om då?

**Comment by isabellaalstrom** [comment]
Ska testa! Fick själv inte till sensorn alls.

**Comment by krissen** [comment]
😳Nu får jag inte fram sensorn heller. Funkade bra ännu i... imorse. 🤷‍♂️

**Comment by isabellaalstrom** [comment]
"Sälg / Vide" funkar bra för mig nu. Ska fixa så det funkar i kortet med.

**Comment by isabellaalstrom** [comment]
Borde vara löst nu! Man behöver dra ner nya bilderna, eller döpa om sina gamla till korrekt namn.
