### ISSUE TITLE
Images for "asp" is missing.

### ISSUE THREAD

**Issue by hnnweb** [isabellaalstrom/pollenkoll-card#22]
No images for "asp" in repository

**Comment by isabellaalstrom** [comment]
As far as I know Asp is longer reported?

**Comment by hnnweb** [comment]
https://pollenkoll.se/pollenprognos/nassjo/


Finns med här

**Comment by isabellaalstrom** [comment]
Jag ser att den finns med i listan längre ner, men jag hittar inga bilder för det. Får du in den som sensor?

**Comment by hnnweb** [comment]
Asp verkar ha ersatts av Ambrosia enligt Naturhistoriska Riksmuseet.
