### ISSUE TITLE
Minimal: kortet kapas om utrymmet är smalt

### ISSUE THREAD

**Issue by krissen** [isabellaalstrom/pollenkoll-card#4]
Om utrymmet är för smalt så kapas kortet bara av, istället för att automatiskt öka / minska i storlek

![skarminspelning](https://user-images.githubusercontent.com/2943684/55786233-23a2dd80-5ab4-11e9-9c6a-2a228d179e5c.gif)

Vore bra om bilderna antingen växte / krympte, eller om det skedde radbrytning.

Som det är nu syns t. ex. bara sex kolumner, när jag öppnar sidan på telefonen; utanför vyn finns ytterligare två.

**Comment by isabellaalstrom** [comment]
Tack, ska titta på hur jag ska lösa detta.

**Comment by isabellaalstrom** [comment]
Borde vara löst nu!
