### ISSUE TITLE
Ambrosia

### ISSUE THREAD

**Issue by folrewef** [isabellaalstrom/pollenkoll-card#5]
Finns även en rapport om ambrosia

**Comment by krissen** [comment]
Finns även stöd för ambrosia i kortet; bara att lägga till i din lovelace-config?

```
- type: custom:pollenkoll-card
  [...]
  allergens:
    - ambrosia
    [...]
```

![Skärmklipp 2019-04-09 13 05 28](https://user-images.githubusercontent.com/2943684/55795495-3b845c80-5ac8-11e9-99b5-bc7aed10270f.png)
