### ISSUE TITLE
Kanske lösningen

### ISSUE THREAD

**Issue by ToddTheOdd** [isabellaalstrom/pollenkoll-card#6]
Det här kanske kan vara lösningen för flera/någon av er.
I er configuration.yaml:
  - platform: pollenniva
    scan_interval: 4
    state_as_string: false
    sensors:
      - city: Skövde
        days_to_track: 4
        allergens: 
          - Al
          - Alm
          - Ambrosia
          - Björk
          - Bok
          - Ek
          - Gräs
          - Gråbo
          - Hassel
          - Sälg / Vide
Lägg där märke till hur Sälg / Vide ser ut. Det är för att den ska plockas upp korrekt som sensor. 4 som days_to_track för att jag vill ha dagens pollenprognos och 3 dagar till, alltså så många dagar man kan få från pollenprognos.se även om bara pollenkoll-card bara visar 3 dagar.
Förändringar i pollen-card.js:
Från
      else if (allergen == "sälg") {
        allergen = "salg"
      }
till
      else if (allergen == "sälg") {
        allergen = "salg_vide"
      }
Sedan byta namn på alla filerna som börjar på salg*.svg till salg_vide*.svg i pollen_img mappen i www.

**Comment by isabellaalstrom** [comment]
Jag släpper strax lösning på detta.
