### ISSUE TITLE
Feature request: visa inte allergener med inga halter/uppgifter

### ISSUE THREAD

**Issue by fnordpojk** [isabellaalstrom/pollenkoll-card#9]
Idag får jag en lång lista varav mer än hälften är "inga halter". Det vore fint att ha en option att bara visa de allergener som har några halter i listan.

**Comment by isabellaalstrom** [comment]
Gjort i 0.2.0

**Comment by fnordpojk** [comment]
Jag får tyvärr inte threshold att funka enligt dokumentationen, sätter jag den till 0 så visar den alla allergener, även de utan halter, jag måste sätta den till 1 för att bara visa de som har värden. Det kanske är så det är tänkt att funka, men jag läser inte dokumentationen så :)

**Comment by isabellaalstrom** [comment]
Sätter du den till 0 visar den alla sensorer med värde 0 eller mer, men inte i.u. eller unknown.
Från readme: " (**set to 0 to only exclude unknown or i.u.**)."
